version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    environment:
      ENV: "dev"
    dependencies:
      pre:
        - pip install mozdownload mozinstall
        - mozdownload --version 57.0.4 --destination firefox.tar.bz2
        - mozinstall firefox.tar.bz2
        - wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
        - gunzip -c geckodriver.tar.gz | tar xopf -
        - chmod +x geckodriver && mv geckodriver /home/ubuntu/bin/
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running unit tests
          command: |
            . venv/bin/activate
            cd superlists
            python3 manage.py test lists
      - run:
          name: Running functional tests
          command: |
            . venv/bin/activate
            cd superlists
            python3 manage.py test functional_tests
      - store_artifacts:
          path: test-reports/
          destination: python_app