# This is a basic workflow that is manually triggered

name: Deploy to Heroku
#on:
#  workflow_dispatch:

# temporariamente autmatico
on:
  push:
    branches: [ testci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#    - name: Login to Heroku Container registry
#      env:
#        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#      run: heroku login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
#        heroku git:clone -a ${{ secrets.HEROKU_APP_NAME }}
#        \cp superlists/* ${{ secrets.HEROKU_APP_NAME }}
#        cd ${{ secrets.HEROKU_APP_NAME }}
#        git add .
#        git commit "deploy"
#        git push heroku master
#        heroku run python manage.py migrate
