# This is a basic workflow that is manually triggered

name: Deploy to Heroku
#on:
#  workflow_dispatch:

# temporariamente autmatico
on:
  push:
    branches: [ testci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Add remote origin
      run: |
        cp superlists ${{ secrets.HEROKU_APP_NAME }}
        cd ${{ secrets.HEROKU_APP_NAME }}
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Deploy to Heroku
      run: |
        cd ${{ secrets.HEROKU_APP_NAME }}
        git push heroku HEAD:master -f
